# Configuration file for testing the Forest Diffusion Model

# General settings
local_path: "/home/s.fiscale/conda/Models/forest_diffusion/"
inpath: "trained_models/"

# Training and test split ratios
train_split: "90"  # Split ratio for training set (used in model filename)
test_split: "100"  # Split ratio for the test set

# Model and test set filenames
model_name: "forest_kepler_q1-q17_dr24_split90_nt25_k10_nb70.pkl"  # Name of the trained model to load
test_set_name: "tess_exofop_spoc-qlp_split100"  # Name of the test dataset (without extension)

# Paths derived from input variables
test_catalog: "/home/s.fiscale/conda/Models/forest_diffusion/data/tess_exofop_spoc-qlp_split100.csv"
