# Configuration file for training the Forest Diffusion Model

# General settings
local_path: "/home/s.fiscale/conda/Models/forest_diffusion/"
train_set_name: "kepler_q1-q17_dr25_split100_features_"  # Name of the dataset (features or global views)
train_model_on_global_views: False  # Whether to train on global views or extracted features

# Input and output
input_catalog: "data/kepler_q1-q17_dr25_split100_features_.csv"  # Path to input catalog
output_dir: "/home/s.fiscale/conda/Models/forest_diffusion/trained_models/"  # Directory to save the trained model
model_name: "forest_kepler_q1-q17_dr25_split100_features_nt25_k10_nb70.pkl"  # Model filename

# Model hyperparameters
n_t: 25  # Number of trees or diffusion steps
k: 10  # Number of duplicates (for K-nearest neighbors)
n_batch: 70  # Batch size for training

# Data-specific settings.
bin_indexes: []  # Binary indexes (if any)
cat_indexes: []  # Categorical indexes (if any)
int_indexes: []  # Integer indexes (if any)

# Model options
diffusion_type: "flow"  # Type of diffusion
n_jobs: -1  # Number of jobs for parallel computation
seed: 1  # Random seed for reproducibility
